-- Phase 2D: invoices — one per captured/offline-confirmed payment.
-- Generated server-side (Phase 2G/2H), never by the client.

create sequence public.invoice_number_seq;

create table public.invoices (
  id uuid primary key default gen_random_uuid(),
  payment_id uuid not null unique references public.payments (id) on delete cascade,
  member_id uuid not null references public.profiles (id) on delete cascade,
  invoice_number text not null unique
    default ('INV-' || to_char(now(), 'YYYY') || '-' || lpad(nextval('public.invoice_number_seq')::text, 5, '0')),
  amount_paise integer not null check (amount_paise > 0),
  issued_at timestamptz not null default now(),
  pdf_url text,
  created_at timestamptz not null default now()
);

comment on table public.invoices is
  'One per paid payment. invoice_number defaults to a sequential INV-<year>-##### number; pdf_url is populated once Phase 2H generates the document.';

create index invoices_member_id_idx on public.invoices (member_id);

alter table public.invoices enable row level security;

create policy "invoices_select_own_or_staff"
  on public.invoices for select
  to authenticated
  using (
    member_id = auth.uid()
    or public.current_user_role() in ('owner', 'manager', 'receptionist')
  );

-- Invoices are generated by server-side code alongside a captured/offline
-- payment (Phase 2G/2H), using the service-role client — no client-side
-- insert/update/delete policy is needed for any role.
